In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])

In [6]:
a = [1,2,3,4,5]

In [7]:
np.array(a)

array([1, 2, 3, 4, 5])

In [8]:
l = [[1,2,3], [4,5,6],[7,8,9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
arr = np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [23]:
np.random.rand(10)

array([0.26597403, 0.22015229, 0.1685426 , 0.61866426, 0.06707224,
       0.42828984, 0.39249702, 0.31088282, 0.73394346, 0.89403217])

In [25]:
np.random.randn(10)

array([ 1.25675124, -0.16139772, -1.73471492, -0.8755661 , -0.94385951,
        1.12116095, -0.76862151,  0.69727685, -2.01951406, -0.80680233])

In [29]:
np.random.randint(10,20)

12

In [31]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr.shape

(3, 3)

In [43]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [44]:
arr.mean()

np.float64(5.0)

In [45]:
arr.std()

np.float64(2.581988897471611)

arr.argmin()
arr

In [46]:
arr.argmin()

np.int64(0)

In [48]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [49]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])