In [1]:
import numpy as np

In [4]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [12]:
a1 + a2 

array([ 7,  9, 11, 13, 15])

In [7]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [13]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [14]:
l = [10,20,30,40,50]
arr = np.array(l)

In [15]:
arr + 10

array([20, 30, 40, 50, 60])

In [17]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [20]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
slice = a[:5]
slice = slice * 10

In [28]:
slice

array([10, 20, 30, 40, 50])

In [29]:
A = np.array([[1, 2] , [3,4]])
B = np.array([[5, 6], [7, 8]])

In [30]:
A

array([[1, 2],
       [3, 4]])

In [31]:
B

array([[5, 6],
       [7, 8]])

In [32]:
A @ B

array([[19, 22],
       [43, 50]])

In [33]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [36]:
A.T

array([[1, 3],
       [2, 4]])

In [41]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [42]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [45]:
c = np.arange(16).reshape(4,4)

In [46]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.hsplit(c, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [53]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]