In [1]:
import numpy as np

In [4]:
#Create a 5x5 array containing numbers from 1 to 25 (use reshape), then print its 2nd row and its last column.
arr = np.arange(1, 26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
arr[1:2]

array([[ 6,  7,  8,  9, 10]])

In [16]:
arr[:,-1]

array([ 5, 10, 15, 20, 25])

In [20]:
#Create a 1D array of 20 random integers (between 1 and 100), then extract only the even numbers from it using boolean indexing.
arr = np.random.randint(1,101,20)
arr[arr % 2 == 0]

array([22, 98,  6, 90, 26, 54, 46, 38], dtype=int32)

In [30]:
# Reverse a NumPy array without using a loop, using a slicing trick (don't use the simple arr[::-1] — try a different slicing approach to achieve the same result).
a = np.array([1,2,3,4])
np.flip(a)

array([4, 3, 2, 1])

In [38]:
# Create two arrays - one with shape (3,1) and another with shape (1,4). Add them together using broadcasting, and observe what shape the result comes out to be.
A = np.array([1,2,3]).reshape(3,1)
B = np.array([5,6,7,8]).reshape(1,4)
A + B

array([[ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11]])

In [50]:
#Take an array, and compute its square root, square, and cube all together — then stack the three results as columns into one array (using np.column_stack).A
arr = np.array([1,4,9,16])
a = np.sqrt(arr)
b = np.square(arr)
c = arr ** 3
np.column_stack([a, b, c])

array([[1.000e+00, 1.000e+00, 1.000e+00],
       [2.000e+00, 1.600e+01, 6.400e+01],
       [3.000e+00, 8.100e+01, 7.290e+02],
       [4.000e+00, 2.560e+02, 4.096e+03]])

In [51]:
#Create an array of Celsius temperatures, then convert it to Fahrenheit using the formula F = C*9/5 + 32, all in a single line (no loop needed).
C = np.array([20,35,40,8])
F = C * (9/5) + 32

print(F)



[ 68.   95.  104.   46.4]


In [56]:
#Create a 4x4 array of random numbers, then compute the row-wise sum, column-wise mean, and the overall maximum value.
A = np.random.randint(1,50,(4,4))
A

array([[49, 41, 37, 36],
       [36, 11, 37, 14],
       [15, 37, 35,  4],
       [21, 11,  5,  4]], dtype=int32)

In [57]:
np.sum(A, axis=1)

array([163,  98,  91,  41])

In [58]:
np.mean(A, axis=0)

array([30.25, 25.  , 28.5 , 14.5 ])